version: "3"
services:
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGO_IP: mongo-database
      MONGO_PORT: 27017
      MONGO_USER: matteodatabase
      MONGO_PASSWORD: mypassword
    command: npm run start
  mongo-database:
     environment:
      MONGO_INITDB_ROOT_USERNAME: matteodatabase
      MONGO_INITDB_ROOT_PASSWORD: mypassword
      

